:memo: Reorder assert overloads to render better documentation
dubzzz/fast-check pull request #2750
Opened 2022-02-22 22:32 UTC by gibson042

Fixes #2749

**_Category:_**

- [ ]  Introduce new features
- [x]  Add or update documentation
- [ ]  Add or update tests
- [ ]  Fix a bug
- [ ]  Add or update types
- [ ]  Improve performance
- [ ] _Other(s):_ ...

**_Potential impacts:_**

- [ ] Generated values
- [ ] Shrink values
- [ ] Performance
- [ ] Typings
- [x] _Other(s):_ [API reference documentation](https://dubzzz.github.io/fast-check/index.html#assert)

2022-02-22 22:38 UTC, dubzzz commented
Seems that the change introduces a breaking change 🤔

2022-02-22 23:53 UTC, gibson042 commented
@dubzzz Fixed (:crossed_fingers:)

2022-02-23 08:10 UTC, dubzzz commented on src/check/runner/Runner.ts
> +): Promise<void> | void;
I'm not sure to understand the need behind this move of the overload higher in the ordering. It seems that with the current setup (the one before your PR) the overloads gets properly shown in IDEs like VSCode.

Here is what I get for `asyncProperty`:
![image](https://user-images.githubusercontent.com/5300235/155281263-92e5dd73-3dc3-4e95-be82-6b932bfe81cc.png)

And for `property`:
![image](https://user-images.githubusercontent.com/5300235/155281647-abbbbcc5-dff5-44e3-bce8-e2f8fb24b958.png)

Your problem mostly be related to things being written in the current documentation and not with the ordering of those overloads.

Additionally as it worked well up to now, and to limit risks of regressions I'd not add complexity (Exclude... were not needed in the past, they make typings harder to read for non-ts users) on the typings for not needed reasons.

2022-02-23 08:12 UTC, dubzzz requested changes
Not sure to get the reason of the PR. In the documentation only the `asyncProperty` version is marked as "WARNING: Has to be awaited". The sync version does not have the comment and is the one shown in the IDE.

Both are generated in the documentation because they have to be. So yes the message "WARNING: Has to be awaited" is shown but only for the signature with async which is expected.

2022-02-23 17:45 UTC, gibson042 commented
Oh, I didn't realize that the signatures were independently selectable. This is more like an API reference page usability issue, but I'm not sure where to fix it. In the meantime, I've updated this PR to restore the current overload signature order.

2022-02-23 21:22 UTC, gibson042 commented
@dubzzz Addressed with custom CSS.

**light mode**
![light](https://user-images.githubusercontent.com/1199584/155410558-40443c87-2710-4aae-94f3-82d6b99e4c38.png)

**dark mode**
![dark](https://user-images.githubusercontent.com/1199584/155410580-4a886b46-aebf-41cb-8d80-2a6ffd9c6b41.png)

2022-03-02 22:28 UTC, dubzzz commented
Will check the PR in the coming days, sorry for the delay. Coming back soon

2022-03-08 00:31 UTC, dubzzz approved these changes

2022-03-08 00:33 UTC, dubzzz commented
Sorry for the delay, once again thank for the update plus the dark mode. I just relaunched the tests just in case (mostly for prettier, tsdoc and other scripts that may complain for things like comments...).

2022-03-08 00:37 UTC, merged